### ISSUE TITLE
Not working at Purpur-2113 with Velocity 3.3.0-SNAPSHOT (git-7ca06899-b362)

### ISSUE THREAD

**Issue by kit8379** [Elytrium/LimboReconnect#21]
The title message of reconnecting does not print out. And if i try to type something in chat it disconnected me in a sudden.

`[18:05:23 INFO]: [server connection] TonyPak386 -> skymob has disconnected
[18:05:23 INFO] [limboreconnect]: Component: TextComponentImpl{content="伺服器重啟中", style=StyleImpl{obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, color=NamedTextColor{name="yellow", value="#ffff55"}, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[18:05:23 INFO] [limboreconnect]: Kick message: 伺服器重啟中
[18:05:23 INFO] [limboreconnect]: Config: .*重啟中.*
[18:05:23 INFO] [limboreconnect]: Match: true
[18:05:33 INFO]: [connected player] TonyPak386 (210006239254.ctinets.com/210.6.239.254:14492) has disconnected: §c無法連接至伺服器,你已被傳送回大堂
[18:05:33 ERROR]: [connected player] TonyPak386 (210006239254.ctinets.com/210.6.239.254:14492): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@2503e82c
java.lang.IllegalStateException: Not connected to server!
        at com.velocitypowered.proxy.connection.backend.VelocityServerConnection.ensureConnected(VelocityServerConnection.java:215) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at com.velocitypowered.proxy.protocol.packet.chat.ChatQueue.queuePacket(ChatQueue.java:60) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at com.velocitypowered.proxy.protocol.packet.chat.session.SessionChatHandler.handlePlayerChatInternal(SessionChatHandler.java:54) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at com.velocitypowered.proxy.protocol.packet.chat.session.SessionChatHandler.handlePlayerChatInternal(SessionChatHandler.java:32) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at com.velocitypowered.proxy.protocol.packet.chat.ChatHandler.handlePlayerChat(ChatHandler.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler.handle(ClientPlaySessionHandler.java:233) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at com.velocitypowered.proxy.protocol.packet.chat.session.SessionPlayerChatPacket.handle(SessionPlayerChatPacket.java:94) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:153) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:92) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-7ca06899-b362)]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]`

**Comment by SkyWatcher2019** [comment]
Share your config and `/velocity dump`

**Comment by kit8379** [comment]
[velocity-dump-2024-03-10-18-22-18.json](https://github.com/Elytrium/LimboReconnect/files/14549786/velocity-dump-2024-03-10-18-22-18.json)

**Comment by kit8379** [comment]
Is there any update?
