### ISSUE TITLE
1.20.5 not working due to ProvisionException

### ISSUE THREAD

**Issue by SecretlyJealous** [Elytrium/LimboReconnect#22]
```
[07:55:44] [main/ERROR] [com.velocitypowered.proxy.plugin.VelocityPluginManager]: Can't create plugin limboreconnect
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NoSuchElementException: No value present
  at LimboReconnect.<init>(LimboReconnect.java:74)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating LimboReconnect

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
LimboReconnect:         "net.elytrium.limboreconnect.LimboReconnect"
VelocityPluginModule:   "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:134) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:364) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:241) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
Caused by: java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
	at net.elytrium.limboreconnect.LimboReconnect.<init>(LimboReconnect.java:87) ~[?:?]
	at net.elytrium.limboreconnect.LimboReconnect$$FastClassByGuice$$265cbd.GUICE$TRAMPOLINE(<generated>) ~[?:?]
	at net.elytrium.limboreconnect.LimboReconnect$$FastClassByGuice$$265cbd.apply(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[server.jar:3.3.0-SNAPSHOT (git-3afd687b-b381)]
	... 6 more
```

**Comment by MagicTeaMC** [comment]
because Limbo* not support 1.20.5 yet

**Comment by UserNugget** [comment]
Not a LimboReconnect issue, but anyway, fixed in the latest LimboAPI release
