### ISSUE TITLE
Not connected to server!

### ISSUE THREAD

**Issue by VINRED5** [Elytrium/LimboReconnect#23]
```
[17:00:35 INFO]: [connected player] boberKurva (/95.24.21.170:64487) has disconnected: В вашем подключении произошла внутренняя ошибка.
[17:00:35 ERROR]: [connected player] boberKurva (/95.24.21.170:64487): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@86d677
java.lang.IllegalStateException: Not connected to server!
        at com.velocitypowered.proxy.connection.backend.VelocityServerConnection.ensureConnected(VelocityServerConnection.java:220) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at com.velocitypowered.proxy.protocol.packet.chat.ChatQueue.queuePacket(ChatQueue.java:60) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at com.velocitypowered.proxy.protocol.packet.chat.CommandHandler.queueCommandResult(CommandHandler.java:58) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at com.velocitypowered.proxy.protocol.packet.chat.session.SessionCommandHandler.handlePlayerCommandInternal(SessionCommandHandler.java:46) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at com.velocitypowered.proxy.protocol.packet.chat.session.SessionCommandHandler.handlePlayerCommandInternal(SessionCommandHandler.java:29) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at com.velocitypowered.proxy.protocol.packet.chat.CommandHandler.handlePlayerCommand(CommandHandler.java:42) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler.handle(ClientPlaySessionHandler.java:216) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at com.velocitypowered.proxy.protocol.packet.chat.session.SessionPlayerCommandPacket.handle(SessionPlayerCommandPacket.java:72) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:153) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:92) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by VINRED5** [comment]
Velocity 3.3.0-SNAPSHOT (git-a9a31f69-b385)
