### ISSUE TITLE
Ошибка LimboReconnect при перезагрузки игрового сервера

### ISSUE THREAD

**Issue by KLOFFFF** [Elytrium/LimboReconnect#30]
### Подробности
1. Скачан с **GitHub** - [LimboAPI](https://github.com/Elytrium/LimboAPI/actions/runs/11112181374)
  - Изменения:
     - `compatibility-mode: с false на true`
2. Скачан с **GitHub** - [PacketEvents](https://github.com/retrooper/packetevents/actions/runs/11238951421)
3. Скачан с **Modrinth** - [LimboReconnect 1.1.5](https://modrinth.com/plugin/limboreconnect/version/1.1.5)
  - Так же проблемы с версиями:
     - Скачан с **GitHub** - [LimboReconnect 1.1.4](https://github.com/Elytrium/LimboReconnect/releases/tag/1.1.4)

### Лог ошибки
1. [exception encountered in net.elytrium.limboapi.server.LimboSessionHandlerImpl@15a43f23
 io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unable to find id
 for packet of type net.elytrium.limboapi.protocol.packets.s2c.ChangeGameStatePacket in
 CLIENTBOUND protocol 1.20.3 phase PLAY](https://api.mclo.gs/1/raw/AOZ1h46)

![image](https://github.com/user-attachments/assets/2ac6f638-d67a-4776-a112-894d650a801f)

### Как это проявляется ?
- Когда основной сервер выполняет перезагрузку в основном командой `/stop` игрока
 кикает с сервера, так-же с помощью команды `/restart`.
 
 ![image](https://github.com/user-attachments/assets/92fe569d-1bb5-4123-97cd-b889f8a46710)
 
 ```
📁 minecraft
├── 📁 proxy
│   ├── 📁 lang
│   ├── 📁 logs
│   │   └── 📑 logs.txt
│   ├── 📁 plugins
│   │   ├── 📁 limboapi
│   │   │   └── 📑 config.yml
│   │   │          compatibility-mode: true
│   │   │
│   │   ├── 📑 LimboAPI.jar
│   │   ├── 📑 PacketEvents.jar
│   │   └── 📑 LimboReconnect-1.1.5.jar
│   │
│   │              
│   ├── 📑 forwarding.secret
│   ├── 📑 Script.sh
│   ├── 📑 Core.jar
│   └── 📑 Velocity.toml
└── 📁 general
 ```

**Comment by SkyWatcher2019** [comment]
Try [6a3e799](https://github.com/Elytrium/LimboReconnect/releases/tag/dev-build)

**Comment by SkyWatcher2019** [comment]
```
[21:51:59 WARN] [limboreconnect]: Looks like you using default config!
[21:51:59 WARN] [limboreconnect]: Please check 'trigger-message' option and confirm, that it matches your server's restart message
```

**Comment by TheFaik** [comment]
Также!

**Comment by TheFaik** [comment]
```
[12:20:26] [Netty epoll Worker #2/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [connected player] TheFaik (/77.34.74.157:63502): exception encountered in net.elytrium.limboapi.server.LimboSessionHandlerImpl@7ce83066
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unable to find id for packet of type net.elytrium.limboapi.protocol.packets.s2c.ChangeGameStatePacket in CLIENTBOUND protocol 1.21 phase PLAY
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at net.elytrium.limboapi.thirdparty.fastprepare.handler.PreparedPacketEncoder.write(PreparedPacketEncoder.java:89) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:248) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at net.elytrium.limboapi.server.LimboPlayerImpl.writePacket(LimboPlayerImpl.java:79) ~[?:?]
	at net.elytrium.limboapi.server.LimboPlayerImpl.setGameMode(LimboPlayerImpl.java:220) ~[?:?]
	at net.elytrium.limboreconnect.handler.ReconnectHandler.onSpawn(ReconnectHandler.java:60) ~[?:?]
	at net.elytrium.limboapi.server.LimboSessionHandlerImpl.onSpawn(LimboSessionHandlerImpl.java:167) ~[?:?]
	at net.elytrium.limboapi.server.LimboImpl.onSpawn(LimboImpl.java:598) ~[?:?]
	at net.elytrium.limboapi.server.LimboImpl.spawnPlayerLocal(LimboImpl.java:449) ~[?:?]
	at net.elytrium.limboapi.server.LimboImpl.lambda$spawnPlayerLocal$16(LimboImpl.java:538) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalArgumentException: Unable to find id for packet of type net.elytrium.limboapi.protocol.packets.s2c.ChangeGameStatePacket in CLIENTBOUND protocol 1.21 phase PLAY
	at com.velocitypowered.proxy.protocol.StateRegistry$PacketRegistry$ProtocolRegistry.getPacketId(StateRegistry.java:881) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:52) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:32) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[velocity.jar:3.4.0-SNAPSHOT (git-1e6396d6-b440)]
	... 27 more

```
