### ISSUE TITLE
Error LimboReconnect

### ISSUE THREAD

**Issue by TheFaik** [Elytrium/LimboReconnect#32]
[connected player] TheFaik (/127.0.0.1:55307): exception encountered in net.elytrium.limboapi.server.LimboSessionHandlerImpl@439e038
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unable to find id for packet of type net.elytrium.limboapi.protocol.packets.s2c.ChangeGameStatePacket in CLIENTBOUND protocol 1.21 phase PLAY
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at net.elytrium.limboapi.thirdparty.fastprepare.handler.PreparedPacketEncoder.write(PreparedPacketEncoder.java:89) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:248) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at net.elytrium.limboapi.server.LimboPlayerImpl.writePacket(LimboPlayerImpl.java:79) ~[?:?]
        at net.elytrium.limboapi.server.LimboPlayerImpl.setGameMode(LimboPlayerImpl.java:220) ~[?:?]
        at net.elytrium.limboreconnect.handler.ReconnectHandler.onSpawn(ReconnectHandler.java:60) ~[?:?]
        at net.elytrium.limboapi.server.LimboSessionHandlerImpl.onSpawn(LimboSessionHandlerImpl.java:167) ~[?:?]
        at net.elytrium.limboapi.server.LimboImpl.onSpawn(LimboImpl.java:607) ~[?:?]
        at net.elytrium.limboapi.server.LimboImpl.spawnPlayerLocal(LimboImpl.java:458) ~[?:?]
        at net.elytrium.limboapi.server.LimboImpl.lambda$spawnPlayerLocal$18(LimboImpl.java:547) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.IllegalArgumentException: Unable to find id for packet of type net.elytrium.limboapi.protocol.packets.s2c.ChangeGameStatePacket in CLIENTBOUND protocol 1.21 phase PLAY
        at com.velocitypowered.proxy.protocol.StateRegistry$PacketRegistry$ProtocolRegistry.getPacketId(StateRegistry.java:915) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:52) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:32) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[velocity.jar:3.4.0-SNAPSHOT (git-7a9227d5-b444)]
        ... 27 more

**Comment by TheFaik** [comment]
I solved this problem by disabling `compatibility-mode: false`, but a new problem appeared - after the player ends up in LimboReconnect (on a proxy), after rebooting the server, the player automatically cannot log into the server until he restarts it.

**Comment by TheFaik** [comment]
UP

**Comment by TheFaik** [comment]
UP

**Comment by TheFaik** [comment]
UP

**Comment by TheFaik** [comment]
UP
